deps_config := \
	test/overlay/Kconfig \
	test/env/Kconfig \
	test/dm/Kconfig \
	test/Kconfig \
	lib/optee/Kconfig \
	lib/efi_loader/Kconfig \
	lib/efi/Kconfig \
	lib/rsa/Kconfig \
	lib/dhry/Kconfig \
	lib/Kconfig \
	fs/fat/Kconfig \
	fs/ext4/Kconfig \
	fs/Kconfig \
	drivers/watchdog/Kconfig \
	drivers/video/bridge/Kconfig \
	drivers/video/stm32/Kconfig \
	drivers/video/rockchip/Kconfig \
	drivers/video/fonts/Kconfig \
	drivers/video/Kconfig \
	drivers/usb/gadget/Kconfig \
	drivers/usb/host/Kconfig \
	drivers/usb/Kconfig \
	drivers/tpm/Kconfig \
	drivers/timer/Kconfig \
	drivers/thermal/Kconfig \
	drivers/sysreset/Kconfig \
	drivers/spmi/Kconfig \
	drivers/spi/Kconfig \
	drivers/sound/Kconfig \
	drivers/smem/Kconfig \
	drivers/serial/Kconfig \
	drivers/scsi/Kconfig \
	drivers/rtc/Kconfig \
	drivers/reset/Kconfig \
	drivers/remoteproc/Kconfig \
	drivers/ram/stm32mp1/Kconfig \
	drivers/ram/Kconfig \
	drivers/pwm/Kconfig \
	drivers/power/regulator/Kconfig \
	drivers/power/pmic/Kconfig \
	drivers/power/domain/Kconfig \
	drivers/power/Kconfig \
	drivers/pinctrl/broadcom/Kconfig \
	drivers/pinctrl/mvebu/Kconfig \
	drivers/pinctrl/exynos/Kconfig \
	drivers/pinctrl/uniphier/Kconfig \
	drivers/pinctrl/renesas/Kconfig \
	drivers/pinctrl/nxp/Kconfig \
	drivers/pinctrl/meson/Kconfig \
	drivers/pinctrl/Kconfig \
	drivers/phy/marvell/Kconfig \
	drivers/phy/allwinner/Kconfig \
	drivers/phy/Kconfig \
	drivers/pcmcia/Kconfig \
	drivers/pci/Kconfig \
	drivers/nvme/Kconfig \
	drivers/net/pfe_eth/Kconfig \
	drivers/net/phy/Kconfig \
	drivers/net/Kconfig \
	drivers/mtd/ubi/Kconfig \
	drivers/mtd/spi/Kconfig \
	drivers/mtd/nand/Kconfig \
	drivers/mtd/Kconfig \
	drivers/mmc/Kconfig \
	drivers/misc/Kconfig \
	drivers/memory/Kconfig \
	drivers/mailbox/Kconfig \
	drivers/led/Kconfig \
	drivers/input/Kconfig \
	drivers/i2c/muxes/Kconfig \
	drivers/i2c/Kconfig \
	drivers/gpio/Kconfig \
	drivers/fpga/Kconfig \
	drivers/firmware/Kconfig \
	drivers/fastboot/Kconfig \
	drivers/dma/Kconfig \
	drivers/dfu/Kconfig \
	drivers/ddr/fsl/Kconfig \
	drivers/demo/Kconfig \
	drivers/ddr/altera/Kconfig \
	drivers/ddr/Kconfig \
	drivers/crypto/fsl/Kconfig \
	drivers/crypto/Kconfig \
	drivers/cpu/Kconfig \
	drivers/clk/uniphier/Kconfig \
	drivers/clk/tegra/Kconfig \
	drivers/clk/renesas/Kconfig \
	drivers/clk/owl/Kconfig \
	drivers/clk/mvebu/Kconfig \
	drivers/clk/exynos/Kconfig \
	drivers/clk/at91/Kconfig \
	drivers/clk/Kconfig \
	drivers/bootcount/Kconfig \
	drivers/block/Kconfig \
	drivers/axi/Kconfig \
	drivers/ata/Kconfig \
	drivers/adc/Kconfig \
	drivers/core/Kconfig \
	drivers/Kconfig \
	net/Kconfig \
	env/Kconfig \
	dts/Kconfig \
	disk/Kconfig \
	cmd/ti/Kconfig \
	cmd/mvebu/Kconfig \
	lib/efi_selftest/Kconfig \
	cmd/Kconfig \
	common/spl/Kconfig \
	common/Kconfig \
	api/Kconfig \
	arch/arm/Kconfig.debug \
	board/armltd/vexpress64/Kconfig \
	board/armltd/vexpress/Kconfig \
	arch/arm/cpu/armv7/Kconfig \
	arch/arm/cpu/armv7/vf610/Kconfig \
	arch/arm/cpu/armv7/ls102xa/Kconfig \
	arch/arm/Kconfig \
	arch/Kconfig \
	Kconfig

include/config/auto.conf: \
	$(deps_config)

ifneq "$(UBOOTVERSION)" "2018.09"
include/config/auto.conf: FORCE
endif

$(deps_config): ;
